name: test
permissions:
  contents: read

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.2'
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: test
      run: make test
  testacc:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        terraform:
        - 1.0.0
        - 0.15.5
        - 0.14.11
        - 0.13.7
        - 0.12.31
    env:
      TERRAFORM_VERSION: ${{ matrix.terraform }}
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: docker-compose build
    - name: terraform --version
      run: docker-compose run --rm tfschema terraform --version
    - name: testacc
      run: docker-compose run --rm tfschema make testacc
